/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-01 02:29:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.anitel.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signInMemberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"../style/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"../style/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"../style/init.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function confirmId(inputForm) { // inputForm <- this.form 객체 받음\r\n");
      out.write("	if(inputForm.id.value == \"\" || !inputForm.id.value) {\r\n");
      out.write("		alert(\"아이디를 입력하세요!\");\r\n");
      out.write("		return; // 메서드 강제 종료\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 팝업\r\n");
      out.write("	var url = \"confirmId.jsp?id=\" + inputForm.id.value; \r\n");
      out.write("	open(url, \"confirmId\",  \"toolbar=no, location=no, status=no, menubar=no, scrollbars=no resizeable=no, width=300, height=200\");\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div id=\"logo\">\r\n");
      out.write("			<img src=\"../imgs/logo.jpg\" width=\"200px\" height=\"100px\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"button\">\r\n");
      out.write("			<button id=\"notice\">공지사항</button>\r\n");
      out.write("			<button id=\"signin\" onclick=\"window.location='signIn.jsp'\">회원가입</button>\r\n");
      out.write("			<button id=\"login\" onclick=\"window.location='LoginForm.jsp'\">로그인</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	<div id=\"jb-content\">\r\n");
      out.write("		<h1 align=\"center\">사업자회원가입</h1>\r\n");
      out.write("	\r\n");
      out.write("		<form action=\"singInMemberPro.jsp\" method=\"post\" name=\"inputForm\">\r\n");
      out.write("			<h3> 사업자 회원 정보(필수입력)</h3>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>아이디</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"id\" placeholder=\"입력 후 중복 체크 해주세요.\" />\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"button\" value=\"중복체크\" onclick=\"confirmId(this.form)\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>비밀번호</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"password\" name=\"member_pw\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>성명</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"member_name\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>연락처</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"member_phone\" placeholder=\"-없이 숫자만 입력해주세요.\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>E-mail</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"member_email\" /> \r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<h3> 호텔(사업자) 기본 정보(필수입력)</h3>\r\n");
      out.write("			<span></span>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>호텔 이름</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"hotel_name\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>대표자 성명</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"hotel_owner\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>호텔주소</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<select name=\"hotel_area\">\r\n");
      out.write("							<option value=\"서울\">서울</option>\r\n");
      out.write("							<option value=\"부산\">부산</option>\r\n");
      out.write("							<option value=\"대구\">대구</option>\r\n");
      out.write("							<option value=\"인천\">인천</option>\r\n");
      out.write("							<option value=\"경기\">경기</option>\r\n");
      out.write("							<option value=\"광주\">광주</option>\r\n");
      out.write("							<option value=\"대전\">대전</option>\r\n");
      out.write("							<option value=\"울산\">울산</option>\r\n");
      out.write("							<option value=\"경상도\">경상도</option>\r\n");
      out.write("							<option value=\"전라도\">전라도</option>\r\n");
      out.write("							<option value=\"제주도\">제주도</option>\r\n");
      out.write("							<option value=\"충청도\">충청도</option>\r\n");
      out.write("							<option value=\"강원도\">강원도</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<input type=\"text\" name=\"hotel_add\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>호텔 전화번호</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"hotel_phone\" placeholder=\"-없이 숫자만 입력해주세요.\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>사업자 등록 번호</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"reg_num\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>호텔 소개<br />\r\n");
      out.write("						※ 메인 리스트에 노출되는 소개글입니다.\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<textarea rows=\"20\" cols=\"60\" name=\"hotel_intro\"></textarea>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>호텔 수용 동물</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<select name=\"pet_type\" id=\"pet_type\" onChange=\"view(this.value)\">\r\n");
      out.write("							<option value=\"1\" selected >강아지</option>\r\n");
      out.write("							<option value=\"2\">고양이</option>\r\n");
      out.write("							<option value=\"0\">기타</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<input type=\"text\" id=\"pet_etctype\" class=\"hidden\" name=\"pet_etctype\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>호텔 편의시설</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"checkbox\" name=\"util_pool\" value=\"1\"/> 수영장\r\n");
      out.write("						<input type=\"checkbox\" name=\"util_ground\" value=\"1\"/> 운동장\r\n");
      out.write("						<input type=\"checkbox\" name=\"util_parking\" value=\"1\"/> 무료주차\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>호텔 유료서비스</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"checkbox\" name=\"paid_bath\" value=\"1\"/> 목욕서비스\r\n");
      out.write("						<input type=\"checkbox\" name=\"paid_beauty\" value=\"1\" /> 미용서비스\r\n");
      out.write("						<input type=\"checkbox\" name=\"paid_medi\" value=\"1\"/> 동물병원\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div class=\"exp_wrap\">\r\n");
      out.write("				<p class=\"exp_detail_sub\">세부 설명</p>\r\n");
      out.write("				<p class=\"exp_detail_con\"> 호텔의 객실과 요금, 부가시설과 추가 서비스, 그리고 대표 이미지 및 소개 이미지는 가입 후 마이 페이지 - 호텔 관리에서 설정하실 수 있습니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"submit\" value=\"가입하기\" />\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			 <img src=\"../imgs/logo2.png\" width=100px; height=50px;>\r\n");
      out.write("			 <p> 평일 10:00 - 17:00 | anitel@anitel.com <br/>\r\n");
      out.write("			 이용약관 | 취소정책 | 1:1문의 <br/>\r\n");
      out.write("				COPYRIGHT 콩콩이 ALL RIGHT Reserved.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function view(value){\r\n");
      out.write("	var pet_type_sel = document.getElementById('pet_type');\r\n");
      out.write("	var pet_type = pet_type_sel.options[pet_type_sel.selectedIndex].value;\r\n");
      out.write("	var input = document.getElementById('pet_etctype');\r\n");
      out.write("	if(pet_type == 0) {\r\n");
      out.write("		input.classList.replace('hidden', 'show');\r\n");
      out.write("	} else {\r\n");
      out.write("		input.classList.replace('show', 'hidden');\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
