/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-01 01:20:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.anitel.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signInUserForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>일반회원 회원가입폼</title>\n");
      out.write("		<link rel=\"stylesheet\" href=\"../style/style.css\">\n");
      out.write("		<link rel=\"stylesheet\" href=\"../style/reset.css\">\n");
      out.write("		<link rel=\"stylesheet\" href=\"../style/init.css\">\n");
      out.write("	\n");
      out.write("	<script>\n");
      out.write("	function confirmId(inputForm) {\n");
      out.write("		if (inputForm.id.value == \"\" || !inputForm.id.value) {\n");
      out.write("			alert(\"아이디를 입력하세요\");\n");
      out.write("			return;\n");
      out.write("			}\n");
      out.write("			var url = \"confirmId.jsp?id=\" + inputForm.id.value;\n");
      out.write("			open(url, \"confirmId\", \"toolbar=no, location=no, status=no, menubar=no, scrollbars=no, resizable=no, width=300, height=200\");\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("</head>\n");
      out.write("<div id=\"container\">\n");
      out.write("	<div id=\"header\">\n");
      out.write("		<div id=\"logo\">\n");
      out.write("			<img src=\"imgs/logo.jpg\" width=\"200px\" height=\"100px\">\n");
      out.write("		</div>\n");
      out.write("		<div id=\"button\">\n");
      out.write("			<button id=\"notice\">공지사항</button>\n");
      out.write("			<button id=\"signin\">회원가입</button>\n");
      out.write("			<button id=\"login\">로그인</button>\n");
      out.write("		</div>\n");
      out.write("	</div>	\n");
      out.write("	<div id=\"jb-content\">\n");
      out.write("    <h1 align=\"center\"> 회원가입 </h1>\n");
      out.write("	<form action=\"signInUserPro.jsp\" method=\"post\" name=\"inputForm\" onsubmit=\"return check()\">\n");
      out.write("		<h3>회원정보 (필수입력)</h3>\n");
      out.write("		<table>\n");
      out.write("			<tr>\n");
      out.write("				<td>아이디</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"id\" placeholder=\"입력 후 중복 체크해주세요\" /> \n");
      out.write("				</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"button\" value=\"중복체크\" onclick=\"confirmId(this.form)\" />\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td>비밀번호</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"password\" name=\"user_pw\" /> \n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td>성명</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"user_name\" /> \n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td>연락처</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"user_phone\" /> \n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td>E-mail</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"user_email\" /> \n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		<br />\n");
      out.write("		\n");
      out.write("		<h3>반려동물 정보(필수입력)</h3>\n");
      out.write("		<table>\n");
      out.write("			<tr>\n");
      out.write("				<td>반려동물이름</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"pet_name\" /> \n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		<br />\n");
      out.write(" \n");
      out.write("	\n");
      out.write("		<h3>반려동물 정보(선택사항)</h3>\n");
      out.write("		<table>\n");
      out.write("			<tr>\n");
      out.write("				<td>반려동물 종</td>\n");
      out.write("				<td>\n");
      out.write("					  <select name=\"pet_type\">  \n");
      out.write("                        <option value =\"1\">강아지</option>\n");
      out.write("		                <option value =\"2\">고양이</option>\n");
      out.write("		                <option value =\"0\">기타</option>\n");
      out.write("                   </select>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			 <tr> \n");
      out.write("			 	<td>반려동물 성별</td>\n");
      out.write("               <td> \n");
      out.write("                   <input type=\"radio\" name='pet_gender' value=\"1\"/> 수컷 \n");
      out.write("                   <input type=\"radio\" name='pet_gender' value=\"0\"/> 암컷     \n");
      out.write("              </td>\n");
      out.write("           </tr> \n");
      out.write("           <tr>\n");
      out.write("				<td>중성화여부</td>\n");
      out.write("				  <td>\n");
      out.write("                    <input type=\"radio\" name=\"pet_operation\" value=\"1\"> 예 \n");
      out.write("                    <input type=\"radio\" name=\"pet_operation\" value=\"0\"> 아니오\n");
      out.write("               	</td> \n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td>반려동물 나이</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"pet_age\" /> \n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			 <tr>\n");
      out.write("				<td>대형동물 여부</td>\n");
      out.write("				  <td>\n");
      out.write("                    <input type=\"radio\" name=\"pet_big\" value=\"1\"> 20kg 이상 경우 체크해주세요 \n");
      out.write("               	</td> \n");
      out.write("			</tr>  \n");
      out.write("			<tr>\n");
      out.write("			<td colspan=\"2\" align=\"center\"> \n");
      out.write("			<input type=\"submit\" value=\"가입하기\" />\n");
      out.write("			</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</form>\n");
      out.write("	\n");
      out.write("		<div id=\"footer\">\n");
      out.write("			 <img src=\"imgs/logo2.png\" width=100px; height=50px;>\n");
      out.write("			 <p> 평일 10:00 - 17:00 | anitel@anitel.com <br/>\n");
      out.write("			 이용약관 | 취소정책 | 1:1문의 <br/>\n");
      out.write("				COPYRIGHT 콩콩이 ALL RIGHT Reserved.</p>\n");
      out.write("			</div>\n");
      out.write("  </div>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
